# Generated by Django 5.2.7 on 2025-11-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_cliente_email_venta_cliente_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cliente_email',
            new_name='email_cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_nombre',
        ),
    ]
