# Generated by Django 5.2.7 on 2025-11-23 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_ordencompra_costo_unitario_and_more'),
        ('ventas', '0004_rename_cliente_email_venta_email_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='producto_codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
    ]
