# Generated by Django 5.2.7 on 2025-11-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
